# Generated by Django 4.2.3 on 2023-08-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
