# Generated by Django 4.2.3 on 2023-08-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_article_is_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
