# Generated by Django 4.2.3 on 2023-08-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0003_article_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_photo',
            field=models.ImageField(default='images/default.png', upload_to='images/categories/'),
        ),
    ]
